export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"66e9916328b5e30023ac82e4",
				"66ec2ade9710450018a2ee3d",
				"670b9de69335410018c70d3d",
				"66ec498a9710450018a2eee5",
				"66e9916328b5e30023ac82e8"
			]
		},
		"66e9916328b5e30023ac82e4": {
			"id": "66e9916328b5e30023ac82e4",
			"name": "404",
			"pageUrl": "404"
		},
		"66e9916328b5e30023ac82e8": {
			"id": "66e9916328b5e30023ac82e8",
			"name": "index",
			"pageUrl": "index"
		},
		"66ec2ade9710450018a2ee3d": {
			"id": "66ec2ade9710450018a2ee3d",
			"pageUrl": "one-edit",
			"name": "One EDIT"
		},
		"66ec498a9710450018a2eee5": {
			"id": "66ec498a9710450018a2eee5",
			"pageUrl": "tienda1",
			"name": "Inicio - index"
		},
		"670b9de69335410018c70d3d": {
			"pageUrl": "tienda1",
			"id": "670b9de69335410018c70d3d",
			"name": "TIENDA"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"width": ""
		},
		"seo": {
			"favicon_apple_152px": "https://uploads.quarkly.io/66e9916328b5e30023ac82d0/images/Ailer-Cub.png?v=2024-09-19T17:57:59.859Z",
			"favicon_32px": "https://uploads.quarkly.io/66e9916328b5e30023ac82d0/images/Ailer-Gek-Fondo-Transparente-V5.png?v=2024-09-17T14:41:50.894Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/66e9916328b5e30023ac82d0/images/Ailer-Cub-Orange.png?v=2024-10-01T21:22:05.277Z",
			"background_win10": "#000848",
			"og:title": "IALER",
			"og:description": "Chat with a doctor right from your phone, all day and night. No waiting room or appointment needed.",
			"og:image": "https://uploads.quarkly.io/66e9916328b5e30023ac82d0/images/AILER-V4.png?v=2024-09-17T14:26:53.714Z",
			"title": "IALER",
			"description": "Chat with a doctor right from your phone, all day and night. No waiting room or appointment needed.",
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated",
			"customSitemapDomain": "https://ialer.com"
		}
	}
}